### ISSUE TITLE
Using a subclass and XAnyElements

### ISSUE THREAD

**Issue by kevin-margueritte** [jonnyzzz/kotlin.xml.bind#1]
Hi,

I work on dictionary for Android using Kotlin and I use your library in order to serialize my words into XML. I have a problem trying to use XAnyElements and a subclass.

**Sub**

```
class Sub {
    var key by JXML[2] / XAttribute("key")
    var value by JXML[1] / XAttribute("value") - "defaultValue"

    var unknown by JXML / XUnknown

    constructor() {
        this.key = "key"
        this.value = "value"
    }
}
```

**Example**

```
@XRoot(name="root")
class Example {
    var content by JXML / "aaa" / "ggg" / XText
    var attribute by JXML.saveOrder(5) / "aaa" / XAttribute("yohoho")
    var sub by JXML / "sub" / XSub(Sub::class.java)

    var collection by JXML / "parameters" / XElements("param") / "aaa" / XText
    var any by JXML / "parameters" / XAnyElements / XSub(Sub::class.java)

    constructor() {
        this.content = "content"
        this.attribute = "attr"
        this.any = this.any?.plus(Sub()) // this does nothing
    }
}
```

**Main**

```
val e = Example()
val saved = JDOM.save(e)
```

In the Example class I can't add anything to var any. Could you help me for fix this problem please.
Thank for you work and thank in advance,

**Comment by jonnyzzz** [comment]
Found several issues in your code

First, `constructor() { .. }` adds extra construction (a non-primary
constructor). You should use `init { .. }` instead.

Type of this.any is `List<Sub>?`. Default value is null. This means
any?.plus will be null any way.
It can be fixed by either the following expession

```
this.any = (this.any?: listOf()) + Sub() // this does nothing
```

or be settings a default value for any

```
var any by JXML / "parameters" / XAnyElements / XSub(Sub::class.java) - listOf()
```

and the last one. `XAnyElements` cannot be saved back. We have no
information on the XML Element name when persisting it. This deserves
additional issue:)

A minor thing to notice, a JDOM has a #toString that does not print
element internals. I used the following trick to dump the whole tree

``` kotlin
private fun Element?.dump() : String {
  if (this == null) return "<null>"
  return XMLOutputter().apply { format = Format.getPrettyFormat()
}.outputString(this)!!
}
```

**Comment by kevin-margueritte** [comment]
Thank for replying, I fixed several issues, however I don't know how to provide a XML Element name to the XAnyElements. I have this error log : 
`Exception in thread "main" java.lang.RuntimeException: AnyElement must have ROOT / XName in order to report it's name for persistence`

This comes from any$delegate in debug mode : 
`property = {...} "() -> org.jonnyzzz.kotlin.xml.bind.jdom.impl.bind.XBindProperty<[ERROR : Unknown type parameter 0]>"`
Thank in advance,

**Comment by jonnyzzz** [comment]
I checked tests code of the library and found you need to have

var N by JXML / XName

in the Sub class. So the engine is able to put element name into the
deserialized object.

The other option could be to have

var X by JXML / "parameters" / XAnyElements / XSub(Inner::class.java)
- XReadOnly

So it will only read data from any elements. Next it's up to you to have
additional fields to write it back

You may also use XUnknown to make it use JDOM object instead of a typed part

If you know element names, you may use XElements("foo") instead, and it
will work with serialization

**Comment by kevin-margueritte** [comment]
Thank for your advises, all works fine
